backend:
  name: github
  repo: YOUR_GITHUB_USERNAME/twitter-hippo
  branch: main
  auth_endpoint: https://api.netlify.com/api/v1/oauth/github

media_folder: "static/images"
public_folder: "/images"

# Enable editorial workflow for content review
publish_mode: editorial_workflow

# Site URL for preview
site_url: https://your-site-name.netlify.app
display_url: https://your-site-name.netlify.app

# Logo and branding
logo_url: https://your-site-name.netlify.app/images/logo.png

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "text" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Primary Button Text", name: "primary_button", widget: "string" }
              - { label: "Secondary Button Text", name: "secondary_button", widget: "string" }
          - label: "Features"
            name: "features"
            widget: "list"
            fields:
              - { label: "Icon", name: "icon", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - label: "Stats"
            name: "stats"
            widget: "list"
            fields:
              - { label: "Number", name: "number", widget: "number" }
              - { label: "Label", name: "label", widget: "string" }
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Author Name", name: "author", widget: "string" }
              - { label: "Author Title", name: "title", widget: "string" }
          - label: "Community Settings"
            name: "community"
            widget: "object"
            fields:
              - { label: "Community URL", name: "url", widget: "string" }
              - { label: "Community Name", name: "name", widget: "string" }
  
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "site-config.json"
        label: "Site Configuration"
        name: "config"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Site Description", name: "description", widget: "text" }
          - { label: "Primary Color", name: "primary_color", widget: "color" }
          - { label: "Secondary Color", name: "secondary_color", widget: "color" }
          - label: "Social Links"
            name: "social"
            widget: "object"
            fields:
              - { label: "Twitter", name: "twitter", widget: "string" }
              - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
              - { label: "Discord", name: "discord", widget: "string", required: false }